/* ---------- Views: assets, governance, insights, administration ---------- */

/* ===== Step-by-step form helpers ===== */
function wizErrors(D, steps, all) { const E = {}; Object.keys(all).forEach(k => { const si = steps.findIndex(s => s[1].includes(k)); if (D.tried || (D.triedSteps || []).includes(si)) E[k] = all[k]; }); return E; }
function wizBar(form, steps, D) {
  const cur = D.step || 0, max = D.maxStep || 0;
  return `<nav class="wiz" aria-label="Form steps"><ol>${steps.map((s, i) => `<li class="${i < cur ? 'done' : ''} ${i === cur ? 'cur' : ''}"><button type="button" data-act="wiz-go" data-form="${form}" data-i="${i}" ${i > max ? 'disabled' : ''} ${i === cur ? 'aria-current="step"' : ''}><span class="n">${i < cur ? icon('check', 'sm') : i + 1}</span><span class="l">${s[0]}</span></button></li>`).join('')}</ol><div class="wiz-meter"><span style="width:${Math.round(cur / (steps.length - 1) * 100)}%"></span></div></nav>`;
}
function wizHead(steps, D) { const s = steps[D.step || 0]; return `<div class="wiz-head"><span class="eyebrow">Step ${(D.step || 0) + 1} of ${steps.length}</span><h2>${s[0]}</h2><p class="ink2">${s[2]}</p></div>`; }
function wizFoot(form, steps, D, cancelAttr, finalLabel) {
  const cur = D.step || 0, last = cur === steps.length - 1;
  return `<div class="wiz-foot">${cur === 0 ? `<button class="btn" type="button" ${cancelAttr}>Cancel</button>` : `<button class="btn" type="button" data-act="wiz-back" data-form="${form}">${icon('back', 'sm')}Back</button>`}<span class="grow"></span>${!last && (D.maxStep || 0) === steps.length - 1 ? `<button class="btn" type="button" data-act="wiz-save" data-form="${form}">${icon('check', 'sm')}${finalLabel}</button>` : ''}<button class="btn primary" type="submit">${last ? icon('check', 'sm') + finalLabel : 'Next' + icon('chevron', 'sm')}</button></div>`;
}
function sumRow(label, val) { return `<dt>${label}</dt><dd>${val || '<span class="muted">—</span>'}</dd>`; }
function sumGroup(form, i, title, rows) { return `<section class="panel sum"><div class="panel-head"><h3>${title}</h3><span class="grow"></span><button type="button" class="btn ghost sm" data-act="wiz-go" data-form="${form}" data-i="${i}">${icon('edit', 'sm')}Edit</button></div><div class="panel-body"><dl class="kv" style="grid-template-columns:130px 1fr">${rows}</dl></div></section>`; }
const toggleBtn = (on, act, attrs = '', label = '') => `<button type="button" class="toggle ${on ? 'on' : ''}" data-act="${act}" ${attrs} role="switch" aria-checked="${on}" aria-label="${esc(label)}"></button>`;

/* ===== Assets ===== */
const ASSET_EDITABLE = ['Draft', 'Amendment Requested', 'Awaiting Lead submission'];
const isOutdated = a => a.blocks.some(b => { const mm = b.kind === 'module' && modById(b.moduleId); return mm && live(mm) && b.v < live(mm).v; });
const assetTarget = a => a.review && canActOn(me(), a) ? 'asset-review' : 'asset';
function viewAssets() {
  const u = me(); const q = F('aq').toLowerCase();
  const rows = S.assets.filter(a => (!q || (a.name + a.id).toLowerCase().includes(q)) && (!F('aprod') || a.products.includes(F('aprod'))) && (!F('amkt') || a.markets.includes(F('amkt'))) && (!F('atype') || a.type === F('atype')) && (!F('astat') || statusOf(a) === F('astat') || (F('astat') === 'outdated' && isOutdated(a)) || (F('astat') === 'open' && ['Draft', 'Awaiting Lead submission'].includes(statusOf(a))))).sort((a, b) => (b.updatedAt || b.createdAt) - (a.updatedAt || a.createdAt));
  const n = f => S.assets.filter(f).length;
  return pageHead('Assets', 'Materials assembled from approved modules. Any text that is not an approved module is flagged as new content and goes through full MLR review.', canCreateAsset(u) ? btn('Create asset', 'asset-new', 'primary', '', 'plus') : '') +
  statStrip([['Approved', n(a => statusOf(a) === 'Approved'), 'ok', 'Ready to use', 'astat', 'Approved'], ['In review', n(a => statusOf(a) === 'In Review'), 'warn', 'With MLR reviewers', 'astat', 'In Review'], ['Amendment requested', n(a => statusOf(a) === 'Amendment Requested'), 'warn', 'Resume after update', 'astat', 'Amendment Requested'], ['Needs update', n(isOutdated), 'bad', 'Uses an older module version', 'astat', 'outdated'], ['Draft', n(a => ['Draft', 'Awaiting Lead submission'].includes(statusOf(a))), 'dim', 'Being assembled', 'astat', 'open']]) +
  `<div class="toolbar">${searchBox('aq', F('aq'), 'Search assets')}${sel('aprod', F('aprod'), S.products.map(p => [p.id, p.name]), 'All products')}${sel('amkt', F('amkt'), S.markets.map(m => [m.id, m.name]), 'All countries')}${sel('atype', F('atype'), S.materialTypes.map(t => [t.id, t.name]), 'All material types')}${sel('astat', F('astat'), ['Draft', 'Awaiting Lead submission', 'In Review', 'Amendment Requested', 'Rejected', 'Approved'], 'All statuses')}${clearBtn(['aq', 'aprod', 'amkt', 'atype', 'astat'])}<span class="muted" style="margin-left:auto">${rows.length} of ${S.assets.length}</span></div>
  <section class="panel table-wrap">${rows.length ? `<table class="tbl list-tbl"><thead><tr><th>Asset</th><th>Products</th><th>Countries</th><th>Channel</th><th>Content</th><th>Version</th><th>Status</th><th>Owner</th></tr></thead><tbody>${rows.map(a => { const nNew = a.blocks.filter(b => b.kind === 'new').length;
    return `<tr class="click" ${goAttr(assetTarget(a), a.id)} tabindex="0"><td><div class="cell-title"><span class="type-ico">${icon('layers', 'sm')}</span><div><div class="title">${esc(a.name)}</div><span class="mono muted">${a.id} · ${esc(mat(a.type).name)}</span></div></div></td><td>${tagList(a.products, 'p')}</td><td>${tagList(a.markets)}</td><td class="nw">${esc(chan(a.channel).name)}</td><td><div class="content-mix"><span><span class="k-dot ok"></span>${a.blocks.length - nNew} approved</span>${nNew ? `<span><span class="k-dot warn"></span>${nNew} new text</span>` : ''}${isOutdated(a) ? `<span><span class="k-dot bad"></span>Older version</span>` : ''}</div></td><td>${vtag(latest(a).v)}</td><td>${chip(statusOf(a))}</td><td>${userCell(a.owner)}</td></tr>`; }).join('')}</tbody></table>` : '<div class="empty"><h4>No assets match these filters</h4><p>Clear a filter or create a new asset.</p></div>'}</section>`;
}
function blockHTML(a, b, i, editable, reviewMode) {
  if (b.kind === 'new') return `<div class="block new" ${editable ? `draggable="true" data-drag="blk" data-i="${i}"` : ''}><div class="meta">${editable ? `<span class="grip" aria-hidden="true">${icon('grip', 'sm')}</span>` : ''}${icon('edit', 'sm')}${b.approved ? 'Text approved in this asset' : 'New content · not an approved module'}${editable ? blockTools(i, a) : ''}</div><div class="txt">${esc(b.text)}</div>${reviewMode && !b.approved ? `<div class="checks"><span class="x">${icon('alert', 'sm')} Requires your review</span></div>` : ''}</div>`;
  const m = modById(b.moduleId); if (!m) return '';
  const v = verOf(m, b.v) || latest(m); const el = eligibility(m, a); const lv = live(m); const outdated = lv && b.v < lv.v;
  const mt = metaOf(m, v); const k = { headline: 'k-headline', cta: 'k-cta', safety: 'k-safety' }[mtype(mt.type).tone] || '';
  return `<div class="block approved ${k}" ${editable ? `draggable="true" data-drag="blk" data-i="${i}"` : ''}><div class="meta">${editable ? `<span class="grip" aria-hidden="true">${icon('grip', 'sm')}</span>` : ''}${icon('lock', 'sm')}${reviewMode ? 'Approved module · locked' : esc(mtype(mt.type).name)} · <span class="mono" style="text-transform:none">${m.id} v${b.v}</span>${outdated ? `<span class="chip warn">v${lv.v} available</span>` : ''}${editable ? blockTools(i, a) : ''}</div>${v.media ? `<div class="block-media">${mediaView(v.media)}</div><div class="block-rules">${icon('alert', 'sm')}<span><b>Usage rules:</b> ${esc(v.media.usage || '—')}</span></div>` : `<div class="txt">${esc(v.body)}</div>`}
  <div class="checks">${[[el.prodOk ? 'Product match' : 'Different product', el.prodOk], ...el.checks].map(c => `<span class="${c[1] ? '' : 'x'}">${icon(c[1] ? 'check' : 'x', 'sm')} ${esc(c[0])}</span>`).join('')}${outdated && canEditObj(me(), a) && !reviewMode ? `<button class="btn sm" data-act="replace-version" data-asset="${a.id}" data-module="${m.id}">Replace with v${lv.v}</button>` : ''}</div></div>`;
}
function blockTools(i, a) { return `<span class="tools"><button data-act="blk-move" data-i="${i}" data-dir="-1" aria-label="Move up" ${i === 0 ? 'disabled' : ''}>${icon('up', 'sm')}</button><button data-act="blk-move" data-i="${i}" data-dir="1" aria-label="Move down" ${i === a.blocks.length - 1 ? 'disabled' : ''}>${icon('down', 'sm')}</button><button data-act="blk-del" data-i="${i}" aria-label="Remove">${icon('trash', 'sm')}</button></span>`; }
function sheet(a, editable, reviewMode) {
  return `<div class="sheet" ${editable ? `data-drop="sheet" data-id="${a.id}"` : ''}><div class="sheet-head"><img src="${LOGO}" alt="SAJA"><span class="muted" style="font-size:12px;font-weight:700">${esc(mat(a.type).name)} · ${esc(productsTxt(a.products))} · ${esc(a.markets.join(', '))} · ${esc(chan(a.channel).name)}</span></div>
  ${a.blocks.length ? a.blocks.map((b, i) => blockHTML(a, b, i, editable, reviewMode)).join('') : `<div class="drop-hint">${icon('layers')}<b>${editable ? 'Drag approved modules here' : 'No content yet'}</b>${editable ? '<span>or click a module on the left to add it</span>' : ''}</div>`}
  <div class="sheet-foot">${a.disclaimer ? esc(a.disclaimer) : `For healthcare professionals in ${esc(marketsTxt(a.markets))}.`}</div></div>`;
}
function assetValidation(a) {
  const mods = a.blocks.filter(b => b.kind === 'module').map(b => ({ b, m: modById(b.moduleId) })).filter(x => x.m);
  const bad = mods.filter(x => !eligibility(x.m, a).ok); const nNew = a.blocks.filter(b => b.kind === 'new').length;
  const sops = validationIssues(a, 'Asset');
  return { mods, bad, nNew, sops, empty: !a.blocks.length, okAll: !bad.length && a.blocks.length > 0 && !sops.length };
}
function assetActions(a, where) {
  const u = me(); const st = statusOf(a); const owns = canEditObj(u, a); const lv = live(a); let h = '';
  if (a.review && canActOn(u, a) && where !== 'review') h += goBtn('Open review', 'asset-review', a.id, 'primary', 'shieldcheck');
  if (owns && ASSET_EDITABLE.includes(st) && where !== 'assemble') h += goBtn(st === 'Amendment Requested' ? 'Amend in assembly' : 'Edit in assembly', 'assemble', a.id, '', 'edit');
  if (owns && where === 'assemble' && ASSET_EDITABLE.includes(st)) h += goBtn('Preview', 'asset', a.id, '', 'eye') + btn('Save draft', 'asset-save', '', `data-id="${a.id}"`, 'check');
  if (owns && ['Draft', 'Awaiting Lead submission'].includes(st)) h += btn(canSubmit(u) ? 'Submit for review' : 'Send to Lead', 'asset-submit', 'primary', `data-id="${a.id}"`, 'send');
  if (canAmendObj(u, a) && st === 'Amendment Requested') h += btn('Resubmit — resume at ' + a.resume.fn + ' ' + levelName(a.resume.level), 'resubmit-open', 'primary', `data-kind="Asset" data-id="${a.id}"`, 'send');
  if (owns && ['Rejected', 'Approved'].includes(st)) h += btn('Create new version', 'asset-version', st === 'Rejected' ? 'primary' : '', `data-id="${a.id}"`, 'copy');
  if (lv) h += goBtn('Cover letter', 'cover', a.id, '', 'award', ` data-k="Asset" data-v="${lv.v}"`);
  return h;
}
function assetBanners(a) {
  const u = me(); const st = statusOf(a); let b = '';
  if (st === 'Amendment Requested') b += `<div class="banner warn">${icon('undo')}<div class="txt"><b>Amendment requested by ${esc(user(a.resume.by).name)} · ${esc(a.resume.fn + ' ' + levelName(a.resume.level))}</b><p>“${esc(a.resume.note)}” After the owner amends and resubmits, approval <b>resumes at the ${esc(a.resume.fn)} ${esc(levelName(a.resume.level))} step</b>. Earlier approvals in this cycle are kept.</p></div></div>`;
  if (st === 'Rejected') { const r = latest(a).cycles.slice(-1)[0].decisions.slice(-1)[0]; b += `<div class="banner bad">${icon('x')}<div class="txt"><b>Rejected by ${esc(user(r.by).name)} · ${esc(r.fn + ' ' + levelName(r.level))}</b><p>“${esc(r.note)}” Create a new version to resubmit. The new version <b>restarts the full approval cycle</b> from the first step.</p></div></div>`; }
  if (st === 'Awaiting Lead submission') b += `<div class="banner info">${icon('inbox')}<div class="txt"><b>Waiting for a Lead to submit</b><p>Prepared by ${esc(user(a.owner).name)}; a Lead of the same team with the Submit permission submits it for review.</p></div></div>`;
  if (a.review) { const cs = curStep(a); b += `<div class="banner pending">${icon('shieldcheck')}<div class="txt"><b>In review · ${esc(stepLabel(cs))}</b><p>Assigned to ${assigneeFor(cs).map(x => esc(x.name)).join(', ') || 'the ' + esc(cs.fn) + ' team'} · cycle ${a.review.cycle} · waiting ${fmtDur(Date.now() - a.review.stepStartedAt)}.</p></div>${canActOn(u, a) ? goBtn('Open review', 'asset-review', a.id, 'sm primary') : ''}</div>`; }
  const outd = a.blocks.filter(x => { const m = x.kind === 'module' && modById(x.moduleId); return m && live(m) && x.v < live(m).v; });
  if (outd.length) b += `<div class="banner warn">${icon('alert')}<div class="txt"><b>${outd.length} module${outd.length > 1 ? 's have' : ' has'} a newer approved version</b><p>Replace the outdated version in the asset. Swapping in a newer approved version of the same module does not need a new review of that text.</p></div></div>`;
  return b ? `<div class="stack" style="margin-bottom:16px">${b}</div>` : '';
}
function viewAssemble() {
  const a = assetById(UI.route.p.id); if (!a) return viewMissing('Asset');
  if (!ASSET_EDITABLE.includes(statusOf(a))) return viewAsset();
  const V = assetValidation(a); const q = F('asq').toLowerCase(); const tf = F('astf');
  const avail = S.modules.filter(m => { const lm = liveMeta(m); return live(m) && !m.archived && lm.products.some(p => a.products.includes(p)) && (!q || (lm.title + m.id + live(m).body).toLowerCase().includes(q)) && (!tf || lm.type === tf); });
  const inAsset = id => a.blocks.some(b => b.moduleId === id); const wf = wfById(assetWorkflow(a));
  return pageHead(esc(a.name), `<span class="row" style="gap:8px">${chip(statusOf(a))}${vtag(latest(a).v)}<span class="mono">${a.id}</span><span class="muted">·</span>${esc(mat(a.type).name)}</span>`, assetActions(a, 'assemble'), [['Assets', 'assets'], [a.id, 'asset', a.id], ['Assembly']]) +
  assetBanners(a) +
  `<div class="assembly">
   <section class="panel"><div class="panel-head"><h3>Approved modules</h3><span class="chip plain">${avail.length}</span></div>
    <div style="padding:12px 12px 0" class="stack"><div class="toolbar" style="margin:0">${searchBox('asq', F('asq'), 'Search modules')}</div><select class="select" style="height:36px" data-filter="astf" aria-label="Module type">${opt('', tf, 'All module types')}<optgroup label="Content modules">${S.moduleTypes.filter(t => !isMediaType(t.id)).map(t => opt(t.id, tf, t.name)).join('')}</optgroup><optgroup label="Media & document modules">${S.moduleTypes.filter(t => isMediaType(t.id)).map(t => opt(t.id, tf, t.name)).join('')}</optgroup></select>
    <button class="btn" data-act="new-text" data-id="${a.id}">${icon('plus', 'sm')}Add new text</button><p class="muted" style="font-size:11.5px">Showing approved modules for ${esc(productsTxt(a.products))}.</p></div>
    <div class="lib-list">${avail.map(m => { const el = eligibility(m, a); const added = inAsset(m.id); return `<button class="lib-item" data-act="blk-add" data-id="${a.id}" data-module="${m.id}" ${!el.ok || added ? 'disabled' : `draggable="true" data-drag="mod" title="Drag onto the asset, or click to add"`}>${isMediaType(liveMeta(m).type) ? `<span class="lib-thumb">${mediaView(live(m).media, 'thumb')}</span>` : ''}<div class="row nowrap" style="gap:8px"><span class="tag">${esc(mtype(liveMeta(m).type).name)}</span><span class="mono muted">${m.id} · v${live(m).v}</span>${added ? '<span class="chip ok plain" style="margin-left:auto">Added</span>' : el.ok ? `<span style="margin-left:auto;color:var(--accent)">${icon('plus', 'sm')}</span>` : ''}</div><b style="font-size:13px">${esc(liveMeta(m).title)}</b><span class="muted" style="font-size:12px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden">${esc(live(m).body)}</span>${!el.ok ? `<span class="why">${icon('x', 'sm')} Not eligible: ${esc(el.reason)}</span>` : ''}</button>`; }).join('') || '<p class="muted" style="padding:8px">No approved modules match.</p>'}</div></section>
   <div class="canvas">${sheet(a, true, false)}</div>
   <div class="stack props-col"><section class="panel props"><div class="panel-head"><h3>Asset properties</h3></div><div class="panel-body form">
     <div class="field"><label for="ap-name">Asset name</label><input class="input" id="ap-name" data-asset-prop="name" data-id="${a.id}" value="${esc(a.name)}"></div>
     <div class="field"><label for="ap-type">Material type</label><select class="select" id="ap-type" data-asset-prop="type" data-id="${a.id}">${activeOf(S.materialTypes, a.type).map(t => opt(t.id, a.type, t.name)).join('')}</select></div>
     <div class="field"><span class="label">Products</span>${chipSelect('a-products', 'a-toggle', 'products', activeOf(S.products, a.products).map(p => [p.id, p.name, p.area]), a.products, { ph: 'Select products', noun: 'products', manage: 'products', extra: `data-id="${a.id}"` })}</div>
     <div class="field"><span class="label">Countries</span>${chipSelect('a-markets', 'a-toggle', 'markets', activeOf(S.markets, a.markets).map(x => [x.id, x.name, x.id]), a.markets, { ph: 'Select countries', noun: 'countries', manage: 'markets', extra: `data-id="${a.id}"` })}</div>
     <div class="field"><label for="ap-ch">Channel</label><select class="select" id="ap-ch" data-asset-prop="channel" data-id="${a.id}">${activeOf(S.channels, a.channel).map(c => opt(c.id, a.channel, c.name)).join('')}</select></div>
     <div class="field"><label for="ap-aud">Audience</label><select class="select" id="ap-aud" data-asset-prop="audience" data-id="${a.id}">${activeOf(S.audiences, a.audience).map(c => opt(c.id, a.audience, c.name)).join('')}</select></div>
     <div class="field"><label for="ap-owner">Material Owner</label>${isAdmin(me()) || can(me(), 'manage_users') ? `<select class="select" id="ap-owner" data-asset-prop="owner" data-id="${a.id}">${ownerOptions(a.owner).map(u => opt(u.id, a.owner, u.name + ' · ' + roleLabel(u))).join('')}</select>` : `<div class="input" style="display:flex;align-items:center;background:var(--surface-2)">${esc(user(a.owner).name)}</div>`}</div>
     <div class="field"><label for="ap-disc">Local disclaimer</label><textarea class="textarea" id="ap-disc" rows="3" data-asset-prop="disclaimer" data-id="${a.id}" placeholder="Required for some countries — see Validation SOPs">${esc(a.disclaimer || '')}</textarea></div>
     <div class="stack" style="gap:8px"><span class="section-title">Module eligibility</span>
       <div class="check-row">${V.empty ? `<span class="no">${icon('x', 'sm')}</span>No content yet` : `<span class="ok">${icon('check', 'sm')}</span>${V.mods.length} approved module${V.mods.length === 1 ? '' : 's'}`}</div>
       ${['Approved', 'Countries covered', 'Channel', 'Not expired'].map((lbl, k) => { const fails = V.mods.filter(x => !eligibility(x.m, a).checks[k][1]); return `<div class="check-row">${fails.length ? `<span class="no">${icon('x', 'sm')}</span>${esc(lbl)} — ${fails.map(x => x.m.id).join(', ')}` : `<span class="ok">${icon('check', 'sm')}</span>${esc(lbl)}`}</div>`; }).join('')}
     </div>
     ${V.nNew ? `<div class="banner warn">${icon('alert')}<div class="txt"><b>New content detected</b><p>${V.nNew} block${V.nNew > 1 ? 's are' : ' is'} not an approved module and require${V.nNew > 1 ? '' : 's'} full MLR review.</p></div></div>` : ''}
     <div class="stack" style="gap:6px"><span class="section-title">Review route</span><b>${esc(wf.name)}</b><span class="muted" style="font-size:11.5px">${V.nNew ? 'New text → the ' + esc(mat(a.type).name) + ' workflow' : 'Approved modules only → streamlined workflow (Settings)'}</span><div class="wf-inline">${wf.steps.map((s, i) => `<span class="wf-pill">${fnBadge(s.fn)}${isNotify(s) ? 'Email' : esc(s.fn) + ' ' + esc(levelName(s.level))}</span>${i < wf.steps.length - 1 ? '<span class="wf-sep"></span>' : ''}`).join('')}</div></div>
   </div></section>${validationPanel(a, 'Asset')}</div></div>`;
}
function assetSummary(a) {
  const V = assetValidation(a); const l = latest(a); const lv = live(a);
  return `<dl class="kv" style="grid-template-columns:110px 1fr"><dt>Material type</dt><dd>${esc(mat(a.type).name)}</dd><dt>Products</dt><dd>${tagList(a.products, 'p')}</dd><dt>Countries</dt><dd>${tagList(a.markets)} <span class="muted" style="font-size:12px">${esc(marketsTxt(a.markets))}</span></dd><dt>Channel</dt><dd>${esc(chan(a.channel).name)}</dd><dt>Audience</dt><dd>${esc(aud(a.audience).name)}</dd><dt>Workflow</dt><dd>${esc((lastWf(a) || wfById(assetWorkflow(a))).name)}</dd><dt>Content</dt><dd>${V.mods.length} approved modules${V.nNew ? ', ' + V.nNew + ' new text' : ''}</dd><dt>Version</dt><dd>v${l.v} · ${esc(l.status)}</dd><dt>Owner</dt><dd>${esc(user(a.owner).name)}</dd>${lv ? `<dt>Approved</dt><dd>v${lv.v} · ${fmtD(lv.approvedAt)} · ${esc(user(lv.approvedBy).name)}</dd>` : ''}</dl>`;
}
function viewAsset() {
  const a = assetById(UI.route.p.id); if (!a) return viewMissing('Asset');
  const tab = UI.route.p.tab || 'overview';
  const tabs = [['overview', 'Overview'], ['approval', 'Approval'], ['versions', 'Version history', a.versions.length], ['audit', 'Audit trail']];
  return pageHead(esc(a.name), `<span class="row" style="gap:8px">${chip(statusOf(a))}${vtag(latest(a).v)}<span class="mono">${a.id}</span><span class="muted">·</span>${esc(mat(a.type).name)}<span class="muted">·</span>${esc(chan(a.channel).name)}</span>`, assetActions(a, 'asset'), [['Assets', 'assets'], [a.id]]) +
  approvalTimeline(a) + assetBanners(a) + (UI.route.p.v && +UI.route.p.v !== latest(a).v && verOf(a, +UI.route.p.v) ? `<div class="banner info" style="margin-bottom:14px">${icon('book')}<div class="txt"><b>Approved version v${UI.route.p.v}</b><p>The latest version is v${latest(a).v} (${esc(statusOf(a))}). Open the approved version to see exactly what was approved.</p></div>${btn('Open approved v' + UI.route.p.v, 'version-open', 'sm primary', `data-kind="Asset" data-id="${a.id}" data-v="${UI.route.p.v}"`)}</div>` : '') +
  `<div class="tabs" role="tablist" style="margin-bottom:16px">${tabs.map(t => `<button class="tab ${tab === t[0] ? 'active' : ''}" role="tab" aria-selected="${tab === t[0]}" ${goAttr('asset', a.id, ` data-tab="${t[0]}"`)}>${t[1]}${t[2] ? `<span class="n">${t[2]}</span>` : ''}</button>`).join('')}</div>` +
  (tab === 'overview' ? `<div class="grid cols-main"><div class="canvas">${sheet(a, false, false)}</div><div class="stack"><section class="panel"><div class="panel-head"><h3>Summary</h3></div><div class="panel-body">${assetSummary(a)}</div></section>${validationPanel(a, 'Asset')}</div></div>`
    : tab === 'approval' ? viewApprovalTab(a, 'Asset') : tab === 'versions' ? viewVersions(a, 'Asset') : auditTable(S.audit.filter(e => e.objId === a.id), true));
}
function viewAssetReview() {
  const a = assetById(UI.route.p.id); if (!a) return viewMissing('Asset');
  if (!a.review) return pageHead(esc(a.name), 'This asset is not in review.', goBtn('Open asset', 'asset', a.id, 'primary'), [['Approvals', 'tasks'], [a.id]]) + `<div class="banner">${icon('inbox')}<div class="txt"><b>Current status: ${esc(statusOf(a))}</b><p>The review has been completed or moved on.</p></div></div>`;
  const u = me(); const mine = canActOn(u, a); const V = assetValidation(a); const st = curStep(a); const cyc = curCycle(a);
  if (mine && !a.review.startedBy) { a.review.startedBy = u.id; log('Review started', 'Asset', a, null, { note: stepLabel(st) }); save(); }
  return pageHead(esc(a.name), `<span class="row" style="gap:8px">${chip('In Review')}${vtag(latest(a).v)}<span class="mono">${a.id}</span></span>`, mine ? decisionButtons(a, 'Asset') : '', [['Approvals', 'tasks'], [a.id, 'asset', a.id], ['Review']]) +
  (mine ? adminNote(a) : `<div class="banner info" style="margin-bottom:14px">${icon('eye')}<div class="txt"><b>View only — this step is assigned to the ${esc(stepWho(st))}</b></div></div>`) +
  approvalTimeline(a) + `<div class="stack" style="margin-bottom:16px">${authorityBanner(a)}<div class="row"><span class="chip ok">${V.mods.length} approved module${V.mods.length === 1 ? '' : 's'} · locked</span>${V.nNew ? `<span class="chip warn">${V.nNew} new content block${V.nNew > 1 ? 's' : ''} · review required</span>` : '<span class="chip plain">No new content</span>'}</div></div>
  <div class="grid cols-main"><div class="canvas">${sheet(a, false, true)}</div><div class="stack">
  <section class="panel"><div class="panel-head"><h3>What you are approving</h3></div><div class="panel-body stack" style="gap:10px"><div class="check-row"><span class="ok">${icon('check', 'sm')}</span>Approved modules are already MLR-approved and locked — their wording cannot change.</div><div class="check-row"><span class="${V.nNew ? 'no' : 'ok'}">${icon(V.nNew ? 'alert' : 'check', 'sm')}</span>${V.nNew ? 'Review the new content blocks highlighted in amber.' : 'No new content — check placement and context only.'}</div><div class="check-row"><span class="${V.bad.length ? 'no' : 'ok'}">${icon(V.bad.length ? 'x' : 'check', 'sm')}</span>${V.bad.length ? V.bad.length + ' module(s) not eligible' : 'All modules eligible for ' + esc(marketsTxt(a.markets)) + ' · ' + esc(chan(a.channel).name)}</div></div></section>
  ${validationPanel(a, 'Asset')}
  <section class="panel"><div class="panel-head"><h3>Decisions in this cycle</h3></div><div class="panel-body">${decisionsList(cyc.decisions)}</div></section></div></div>`;
}

/* ===== Lifecycle ===== */
const lifeBucket = m => { const ls = lifeStatus(m); return ['Awaiting Lead submission', 'Rejected'].includes(ls) ? 'Draft' : ls === 'Amendment Requested' ? 'In Review' : ls; };
function viewLifecycle() {
  const stage = F('life', 'Expiring');
  const inStage = s => s === 'Superseded' ? S.modules.filter(m => m.versions.some(v => v.status === 'Superseded')) : S.modules.filter(m => lifeBucket(m) === s);
  const rows = inStage(stage);
  const upcoming = S.modules.filter(m => m.expiry && !m.archived && live(m) && daysTo(m.expiry) <= 120).sort((a, b) => a.expiry - b.expiry);
  const reviews = S.modules.filter(m => m.reviewDate && !m.archived && live(m) && daysTo(m.reviewDate) <= S.settings.reviewReminderDays * 3).sort((a, b) => a.reviewDate - b.reviewDate);
  const impactedAll = S.modules.map(m => [m, impactedAssets(m)]).filter(x => x[1].length);
  return pageHead('Lifecycle', `Where every module is in its life — from draft to archive. Modules are flagged as expiring ${S.settings.expiryWarnDays} days before expiry.`, isAdmin(me()) ? goBtn('Lifecycle rules', 'settings', null, '', 'settings') : '') +
  `<section class="panel" style="margin-bottom:18px"><div class="panel-body"><div class="life" role="tablist" aria-label="Lifecycle stages">${LIFE.map((s, i) => `<button class="life-st ${stage === s ? 'on' : ''}" role="tab" aria-selected="${stage === s}" data-act="set-f" data-k="life" data-v="${s}"><span class="k-dot ${toneOf(s) || 'dim'}"></span>${s} <b class="num">${inStage(s).length}</b></button>${i < LIFE.length - 1 ? `<span class="life-arrow">${icon('chevron', 'sm')}</span>` : ''}`).join('')}</div></div></section>
  ${impactedAll.length ? `<div class="stack" style="margin-bottom:18px">${impactedAll.map(([m, list]) => `<div class="banner warn">${icon('alert')}<div class="txt"><b>${list.length} asset${list.length > 1 ? 's use' : ' uses'} a previous version of ${esc(m.title)}</b><p>v${live(m).v} is approved. ${list.map(a => esc(a.name)).join(' · ')}</p></div>${goBtn('Review impact', 'module', m.id, 'sm', '', ' data-tab="lifecycle"')}</div>`).join('')}</div>` : ''}
  <div class="grid cols-main"><section class="panel table-wrap"><div class="panel-head"><h3>${esc(stage)}</h3><span class="chip plain">${rows.length}</span></div>${rows.length ? `<table class="tbl"><thead><tr><th>Module</th><th>Products</th><th>Countries</th><th>Version</th><th>Status</th><th>Review date</th><th>Expiry</th><th>Assets</th></tr></thead><tbody>${rows.map(m => `<tr class="click" ${goAttr('module', m.id, ' data-tab="lifecycle"')}><td><div class="cell-title">${typeIco(m.type)}<div><div class="title">${esc(m.title)}</div><span class="mono muted">${m.id}</span></div></div></td><td>${tagList(m.products, 'p')}</td><td>${tagList(m.markets)}</td><td class="nw">${stage === 'Superseded' ? m.versions.filter(v => v.status === 'Superseded').map(v => vtag(v.v)).join(' ') + ' → ' + (live(m) ? vtag(live(m).v) : '') : vtag(latest(m).v)}</td><td>${chip(stage === 'Superseded' ? 'Superseded' : lifeStatus(m))}</td><td class="num nw">${fmtD(m.reviewDate)}</td><td class="num nw">${fmtD(m.expiry)}</td><td class="num">${S.assets.filter(a => a.blocks.some(b => b.moduleId === m.id)).length}</td></tr>`).join('')}</tbody></table>` : `<div class="empty"><p>No modules in this stage.</p></div>`}</section>
  <div class="stack"><section class="panel"><div class="panel-head"><h3>Upcoming expiries</h3><span class="chip plain">${upcoming.length}</span></div>${upcoming.length ? upcoming.map(m => `<button class="task" ${goAttr('module', m.id, ' data-tab="lifecycle"')}><span class="body"><b>${esc(m.title)}</b><span>${fmtD(m.expiry)} · ${daysTo(m.expiry) < 0 ? 'expired ' + Math.abs(daysTo(m.expiry)) + ' days ago' : daysTo(m.expiry) + ' days'}</span></span>${chip(lifeStatus(m))}</button>`).join('') : '<div class="empty"><p>Nothing expires in the next 120 days.</p></div>'}</section>
  <section class="panel"><div class="panel-head"><h3>Periodic reviews due</h3><span class="chip plain">${reviews.length}</span></div>${reviews.length ? reviews.map(m => `<button class="task" ${goAttr('module', m.id, ' data-tab="lifecycle"')}><span class="body"><b>${esc(m.title)}</b><span>Review ${fmtD(m.reviewDate)} · ${daysTo(m.reviewDate) < 0 ? Math.abs(daysTo(m.reviewDate)) + ' days overdue' : 'in ' + daysTo(m.reviewDate) + ' days'}</span></span>${icon('chevron', 'sm')}</button>`).join('') : '<div class="empty"><p>No periodic reviews due soon.</p></div>'}</section></div></div>`;
}

/* ===== Audit trail ===== */
const AUDIT_CATS = [
  ['Content', /created|edited|version created|changed|reference|content/i],
  ['Approval', /submitted|review|approv|amend|reject|returned|assigned|signed|step/i],
  ['Assets', /asset|reused|replaced/i],
  ['Lifecycle', /supersed|archiv|expir/i],
  ['Administration', /user|role|permission|workflow|sop|setting|product|country|team|material/i],
  ['Notifications', /email/i]
];
const ADMIN_OBJ = ['User', 'Workflow', 'SOP', 'Settings', 'Role', 'Product', 'Country', 'Team', 'Material type', 'Module type', 'Channel', 'Audience', 'Reference', 'Function'];
const auditCat = e => { if (/email/i.test(e.action)) return 'Notifications'; if (ADMIN_OBJ.includes(e.objType) && !/signed/i.test(e.action)) return 'Administration'; if (/supersed|archiv|expir/i.test(e.action)) return 'Lifecycle'; if (/asset created|asset updated|reused|replaced/i.test(e.action)) return 'Assets'; if (/submitted|review|approv|amend|reject|returned|assigned|signed|step/i.test(e.action)) return 'Approval'; return 'Content'; };
const CFG_OF = { Product: 'products', Country: 'markets', 'Module type': 'moduletypes', 'Material type': 'materials', Channel: 'channels', Audience: 'audiences', Reference: 'references', Team: 'teams', Function: 'functions' };
const objLink = e => ({ Module: 'module', Asset: 'asset', User: 'user', Workflow: 'workflow' })[e.objType] || (CFG_OF[e.objType] && CONFIG[CFG_OF[e.objType]].coll().some(x => x.id === e.objId) ? 'item' : null);
function objName(e) { const k = CFG_OF[e.objType]; if (k) { const x = CONFIG[k].coll().find(i => i.id === e.objId); return x ? cfgName(k, x) : e.objId; } if (e.objType === 'Role') return roleName(e.objId); const o = e.objType === 'Asset' ? assetById(e.objId) : e.objType === 'Module' ? modById(e.objId) : e.objType === 'User' ? S.users.find(x => x.id === e.objId) : e.objType === 'Workflow' ? wfById(e.objId) : e.objType === 'SOP' ? S.sops.find(x => x.id === e.objId) : null; return o ? (o.title || o.name) : e.objId; }
function auditTable(rows, compact) {
  rows = [...rows].sort((a, b) => b.ts - a.ts);
  if (!rows.length) return `<section class="panel"><div class="empty"><h4>No audit events</h4><p>${compact ? 'Nothing recorded for this item yet.' : 'No events match these filters.'}</p></div></section>`;
  return `<section class="panel table-wrap"><table class="tbl list-tbl audit-tbl"><thead><tr><th>Date</th><th>Time</th><th>User</th><th>Role</th><th>Action</th>${compact ? '' : '<th>Object</th>'}<th>Version</th><th>Previous → New</th><th>Note</th></tr></thead><tbody>${rows.map(e => { const x = user(e.user); const link = objLink(e); const t = toneOf(e.action);
    return `<tr${link && !compact ? ` class="click" ${goAttr(link, e.objId, link === 'item' ? ` data-k="${CFG_OF[e.objType]}"` : '')}` : ''}><td class="nw num">${fmtD(e.ts)}</td><td class="nw num muted">${fmtT(e.ts)}</td><td><div class="row nowrap user-cell">${avatar(x, 'sm')}<span>${esc(x.name)}</span></div></td><td class="nw" style="font-size:12.5px">${esc(e.role || roleLabel(x))}</td><td><span class="act-line">${t ? `<span class="k-dot ${t}"></span>` : ''}<b>${esc(e.action)}</b></span></td>${compact ? '' : `<td><div style="font-weight:600;max-width:240px">${esc(objName(e))}</div><span class="mono muted">${esc(e.objType)} · ${esc(e.objId)}</span></td>`}<td>${e.objType === 'Module' || e.objType === 'Asset' ? vtag(e.version) : '<span class="muted">—</span>'}</td><td class="pn">${e.prev || e.next ? `<span class="prev">${esc(e.prev || '—')}</span><span class="arr">${icon('arrow', 'sm')}</span><span class="next">${esc(e.next || '—')}</span>` : '<span class="muted">—</span>'}</td><td class="note-cell">${e.note ? esc(e.note) : '<span class="muted">—</span>'}</td></tr>`; }).join('')}</tbody></table></section>`;
}
function auditRows() {
  const q = F('uq').toLowerCase(); const from = fromISO(F('ufrom')), to = fromISO(F('uto'));
  return S.audit.filter(e => { const x = user(e.user);
    return (!q || (x.name + ' ' + e.role + ' ' + e.action + ' ' + e.objId + ' ' + e.note + ' ' + e.prev + ' ' + e.next + ' ' + objName(e)).toLowerCase().includes(q)) && (!F('ucat') || auditCat(e) === F('ucat')) && (!F('uobj') || e.objType === F('uobj')) && (!F('uuser') || e.user === F('uuser')) && (!F('uprod') || (e.products || []).includes(F('uprod'))) && (!F('umkt') || (e.markets || []).includes(F('umkt'))) && (!from || e.ts >= from - 12 * HOUR) && (!to || e.ts <= to + 12 * HOUR); });
}
function viewAudit() {
  const rows = auditRows(); const keys = ['uq', 'ucat', 'uobj', 'uuser', 'uprod', 'umkt', 'ufrom', 'uto'];
  const objTypes = uniq(S.audit.map(e => e.objType)).sort();
  return pageHead('Audit Trail', 'Every action in SAJA MedLR with the person, their role at the time, the object, the version and what changed. Entries cannot be edited or deleted.', can(me(), 'export') ? btn('Export CSV', 'audit-export', '', '', 'download') : '') +
  statStrip(AUDIT_CATS.map(([c]) => [c, S.audit.filter(e => auditCat(e) === c).length, '', 'events', 'ucat', c])) +
  `<div class="toolbar">${searchBox('uq', F('uq'), 'Search people, actions, objects or values')}${sel('ucat', F('ucat'), AUDIT_CATS.map(c => c[0]), 'All actions')}${sel('uobj', F('uobj'), objTypes, 'All objects')}${sel('uuser', F('uuser'), S.users.map(x => [x.id, x.name]), 'All users')}${sel('uprod', F('uprod'), S.products.map(p => [p.id, p.name]), 'All products')}${sel('umkt', F('umkt'), S.markets.map(m => [m.id, m.name]), 'All countries')}<label class="field-inline date-f"><span class="muted">From</span><input type="date" data-filter="ufrom" value="${esc(F('ufrom'))}" aria-label="From date"></label><label class="field-inline date-f"><span class="muted">To</span><input type="date" data-filter="uto" value="${esc(F('uto'))}" aria-label="To date"></label>${clearBtn(keys)}<span class="muted" style="margin-left:auto">${rows.length} of ${S.audit.length} events</span></div>` +
  auditTable(rows, false);
}

/* ===== Reports ===== */
function chartCard(key, title, sub, chart, rows, cols, legend) {
  const mode = F('rv-' + key) || 'chart';
  return `<section class="panel chart-card"><div class="panel-head"><div class="ch-title"><h3>${title}</h3>${sub ? `<span class="muted">${sub}</span>` : ''}</div><span class="grow"></span><div class="seg sm" role="tablist" aria-label="${esc(title)} view">${['chart', 'table'].map(m => `<button type="button" class="${mode === m ? 'on' : ''}" data-act="rv-mode" data-k="${key}" data-v="${m}" role="tab" aria-selected="${mode === m}">${m === 'chart' ? 'Chart' : 'Table'}</button>`).join('')}</div></div>
  <div class="panel-body">${mode === 'chart' ? (legend || '') + chart : `<div class="table-wrap"><table class="tbl compact no-pg"><thead><tr>${cols.map((c, i) => `<th${i ? ' style="text-align:right"' : ''}>${c}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(r => `<tr>${r.map((v, i) => `<td${i ? ' class="num" style="text-align:right"' : ''}>${v}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${cols.length}" class="muted">No data for these filters.</td></tr>`}</tbody></table></div>`}</div></section>`;
}
function hbars(rows, max, cls, fmt) { if (!rows.length) return '<p class="muted">No data for these filters.</p>'; return `<div class="hb">${rows.map(r => `<div class="hb-row"><span class="hb-l">${r[0]}</span><span class="hb-track"><span class="hb-bar ${r[2] || cls || ''}" style="width:${max ? Math.max(r[1] ? 1.5 : 0, 100 * r[1] / max) : 0}%" data-tip="${esc(String(r[0]).replace(/<[^>]+>/g, ''))}: ${fmt ? fmt(r[1]) : r[1]}"></span></span><b class="hb-v">${fmt ? fmt(r[1]) : r[1]}</b></div>`).join('')}</div>`; }
const dd = ms => durDays(ms) + 'd';
const pct = (a, b) => b ? Math.round(100 * a / b) : 0;
const median = a => { if (!a.length) return 0; const s = [...a].sort((x, y) => x - y); const k = Math.floor(s.length / 2); return s.length % 2 ? s[k] : (s[k - 1] + s[k]) / 2; };
const RTABS = [['perf', 'Approval performance'], ['content', 'Content'], ['materials', 'Materials'], ['workflow', 'Workflow'], ['usage', 'Usage']];
function reportCycles() {
  const days = +F('rrange', '180'); const since = days ? Date.now() - days * DAY : 0;
  return allCycles().filter(c => c.start >= since && (!F('rprod') || c.products.includes(F('rprod'))) && (!F('rmkt') || c.markets.includes(F('rmkt'))) && (!F('rtype') || c.type === F('rtype')) && (!F('rwf') || c.wf === F('rwf')));
}
function objFilter(o) { return (!F('rprod') || o.products.includes(F('rprod'))) && (!F('rmkt') || o.markets.includes(F('rmkt'))) && (!F('rtype') || o.type === F('rtype')); }
function viewReports() {
  const tab = UI.route.p.tab || F('rtab', 'perf'); const keys = ['rprod', 'rmkt', 'rtype', 'rwf', 'rstep', 'rrange'];
  const kpi = (v, l, s, tone) => `<div class="kpi static"><span class="k-label">${tone ? `<span class="k-dot ${tone}"></span>` : ''}${l}</span><b>${v}</b><span class="k-sub">${s}</span></div>`;
  const filters = `<div class="toolbar">${sel('rprod', F('rprod'), S.products.map(p => [p.id, p.name]), 'All products')}${sel('rmkt', F('rmkt'), S.markets.map(m => [m.id, m.name]), 'All countries')}${sel('rtype', F('rtype'), [...S.moduleTypes.map(t => [t.id, t.name + ' (module)']), ...S.materialTypes.map(t => [t.id, t.name + ' (material)'])], 'All types')}${sel('rwf', F('rwf'), S.workflows.filter(w => !w.hidden).map(w => [w.id, w.name]), 'All workflows')}${sel('rstep', F('rstep'), reviewFuncs(true), 'All review steps')}<select aria-label="Date range" data-filter="rrange">${[['30', 'Last 30 days'], ['90', 'Last 90 days'], ['180', 'Last 6 months'], ['365', 'Last 12 months'], ['0', 'All time']].map(o => opt(o[0], F('rrange', '180'), o[1])).join('')}</select>${keys.some(k => F(k)) ? btn('Clear filters', 'clear-filters', 'ghost sm', `data-keys="${keys.join(',')}"`) : ''}</div>`;
  const cycles = reportCycles(); const done = cycles.filter(c => c.outcome === 'Approved');
  const times = stepTimes(cycles).filter(x => !F('rstep') || x.fn === F('rstep'));
  let body = '';
  if (tab === 'perf') {
    const by = {}; times.forEach(x => { const k = x.fn + '|' + x.level; (by[k] = by[k] || []).push(x.ms); });
    const stepRows = Object.entries(by).map(([k, a]) => { const [fn, level] = k.split('|'); return { fn, level, n: a.length, avg: avg(a), med: median(a), max: Math.max(...a) }; }).sort((a, b) => reviewFuncs(true).indexOf(a.fn) - reviewFuncs(true).indexOf(b.fn) || (a.level === 'Member' ? -1 : 1));
    const fnAvg = reviewFuncs(true).filter(fn => !F('rstep') || fn === F('rstep')).map(fn => [fn, avg(times.filter(x => x.fn === fn).map(x => x.ms))]);
    const slow = [...stepRows].sort((a, b) => b.avg - a.avg)[0];
    const totalStep = stepRows.reduce((s, r) => s + r.avg * r.n, 0);
    const pend = [...S.modules, ...S.assets].filter(o => o.review && objFilter(o) && (!F('rwf') || o.review.wf === F('rwf')) && (!F('rstep') || curStep(o).fn === F('rstep')));
    const buckets = [['Under 7 days', 0, 7], ['7–14 days', 7, 14], ['14–30 days', 14, 30], ['Over 30 days', 30, 1e9]].map(([l, lo, hi]) => [l, done.filter(c => { const x = (c.end - c.start) / DAY; return x >= lo && x < hi; }).length]);
    const pendBy = reviewFuncs(true).map(fn => [fn, pend.filter(o => curStep(o).fn === fn)]).filter(x => !F('rstep') || x[0] === F('rstep'));
    const mxF = Math.max(1, ...fnAvg.map(x => x[1])); const mxS = Math.max(1, ...stepRows.map(r => r.avg));
    body = `<div class="kpis" style="margin-bottom:18px">${kpi(dd(avg(done.map(c => c.end - c.start))), 'Average approval time', 'Submission to final approval · ' + done.length + ' cycles', '')}${kpi(dd(avg(times.map(x => x.ms))), 'Average time per step', times.length + ' completed steps', '')}${kpi(pend.length, 'Pending approvals', pend.length ? 'Oldest waiting ' + fmtDur(Date.now() - Math.min(...pend.map(o => o.review.stepStartedAt))) : 'Nothing waiting', pend.length ? 'warn' : 'ok')}${kpi(slow ? slow.fn : '—', 'Slowest step', slow ? levelName(slow.level) + ' ' + (slow.level === 'Lead' ? 'approval' : 'review') + ' · ' + dd(slow.avg) + ' on average' : 'No data', slow ? 'bad' : '')}</div>
    ${slow && totalStep ? `<div class="banner warn" style="margin-bottom:18px">${icon('alert')}<div class="txt"><b>Bottleneck: ${esc(slow.fn)} ${esc(levelName(slow.level))} ${slow.level === 'Lead' ? 'approval' : 'review'}</b><p>Averages ${fmtDur(slow.avg)} per item (median ${fmtDur(slow.med)}, longest ${fmtDur(slow.max)}) and accounts for ${pct(slow.avg * slow.n, totalStep)}% of all review time in this period.</p></div></div>` : ''}
    <div class="reports-grid">
    ${chartCard('fnavg', 'Average approval time per review step', 'Medical, Legal and Regulatory · days', hbars(fnAvg.map(([fn, ms]) => [`${fnBadge(fn, 'sm')}${fn}`, ms, slow && slow.fn === fn ? 'o2' : 's1']), mxF, '', dd), fnAvg.map(([fn, ms]) => [fn, dd(ms), times.filter(x => x.fn === fn).length]), ['Review step', 'Average', 'Steps'])}
    ${chartCard('steplvl', 'Time per step by level', 'Member review and Lead approval', `<div class="hb grouped">${reviewFuncs(true).filter(fn => stepRows.some(r => r.fn === fn)).map(fn => `<div class="hb-group"><span class="hb-gl">${fnBadge(fn, 'sm')}${fn}</span>${hbars(stepRows.filter(r => r.fn === fn).map(r => [r.level === 'Lead' ? 'Lead' : 'Member', r.avg, r.level === 'Lead' ? 'o2' : 'o1']), mxS, '', dd)}</div>`).join('') || '<p class="muted">No data for these filters.</p>'}</div>`, stepRows.map(r => [r.fn + ' ' + levelName(r.level), r.n, dd(r.avg), dd(r.med), dd(r.max)]), ['Step', 'Items', 'Average', 'Median', 'Longest'], `<div class="legend"><span><i class="o1"></i>Member review</span><span><i class="o2"></i>Lead approval</span></div>`)}
    ${chartCard('cycdur', 'Approval cycle duration', 'Completed cycles by total duration', hbars(buckets, Math.max(1, ...buckets.map(b => b[1])), 's1'), buckets, ['Duration', 'Cycles'])}
    ${chartCard('pending', 'Pending approvals by step', 'Items waiting now and how long', hbars(pendBy.map(([fn, l]) => [`${fnBadge(fn, 'sm')}${fn}`, l.length]), Math.max(1, ...pendBy.map(x => x[1].length)), 's1'), pend.map(o => [`<button class="linklike" ${goAttr(kindOf(o) === 'Asset' ? 'asset' : 'module', o.id)}>${esc(o.id)}</button> ${esc(stepLabel(curStep(o)))}`, fmtDur(Date.now() - o.review.stepStartedAt)]), ['Item · step', 'Waiting'])}
    </div>`;
  } else if (tab === 'content') {
    const mods = S.modules.filter(objFilter); const ls = m => lifeStatus(m);
    const c = { total: mods.length, approved: mods.filter(m => live(m) && !m.archived).length, review: mods.filter(m => ['In Review', 'Amendment Requested'].includes(ls(m))).length, draft: mods.filter(m => ['Draft', 'Awaiting Lead submission', 'Rejected'].includes(ls(m))).length, expiring: mods.filter(m => ls(m) === 'Expiring' || libraryStatus(m) === 'Expiring').length, sup: mods.reduce((s, m) => s + m.versions.filter(v => v.status === 'Superseded').length, 0) };
    const stages = LIFE.map(s => [s, s === 'Superseded' ? mods.filter(m => m.versions.some(v => v.status === 'Superseded')).length : mods.filter(m => lifeBucket(m) === s).length]);
    const types = S.moduleTypes.map(t => [esc(t.name), mods.filter(m => m.type === t.id).length]);
    const approvedPerMonth = []; for (let i = 5; i >= 0; i--) { const s = new Date(); s.setDate(1); s.setHours(0, 0, 0, 0); s.setMonth(s.getMonth() - i); const e = new Date(s); e.setMonth(e.getMonth() + 1); approvedPerMonth.push([MON[s.getMonth()] + ' ' + String(s.getFullYear()).slice(2), mods.reduce((n, m) => n + m.versions.filter(v => v.approvedAt >= s.getTime() && v.approvedAt < e.getTime()).length, 0)]); }
    body = `<div class="kpis six" style="margin-bottom:18px">${kpi(c.total, 'Total modules', 'Matching the filters', '')}${kpi(c.approved, 'Approved', 'Have a live version', 'ok')}${kpi(c.review, 'In review', 'Incl. amendments', 'warn')}${kpi(c.draft, 'Draft', 'Incl. rejected', 'dim')}${kpi(c.expiring, 'Expiring', 'Within ' + S.settings.expiryWarnDays + ' days', 'warn')}${kpi(c.sup, 'Superseded versions', 'Replaced by a newer version', 'dim')}</div>
    <div class="reports-grid">
    ${chartCard('stage', 'Modules by lifecycle stage', 'Current stage of every module', hbars(stages, Math.max(1, ...stages.map(x => x[1])), 's1'), stages, ['Stage', 'Modules'])}
    ${chartCard('mtype', 'Modules by type', 'Content modules and media & document modules', `<div class="hb grouped">${[['Content modules', false], ['Media & document modules', true]].map(([g, med]) => { const rows = S.moduleTypes.filter(t => isMediaType(t.id) === med).map(t => [esc(t.name), mods.filter(m => m.type === t.id).length, med ? 'o2' : 's1']); return `<div class="hb-group"><span class="hb-gl">${g} · ${rows.reduce((n, r) => n + r[1], 0)}</span>${hbars(rows, Math.max(1, ...types.map(x => x[1])))}</div>`; }).join('')}</div>`, S.moduleTypes.map(t => [esc(t.name), esc(modCategory(t.id)), mods.filter(m => m.type === t.id).length]), ['Module type', 'Category', 'Modules'])}
    ${chartCard('apm', 'Versions approved per month', 'Last 6 months', `<div class="vbars">${approvedPerMonth.map(([l, n]) => `<div class="vb"><span class="vb-v">${n}</span><span class="vb-bar" style="height:${4 + 120 * n / Math.max(1, ...approvedPerMonth.map(x => x[1]))}px" data-tip="${l}: ${n}"></span><span class="vb-l">${l}</span></div>`).join('')}</div>`, approvedPerMonth, ['Month', 'Versions approved'])}
    ${chartCard('exp', 'Expiring and review due', 'Approved modules · next 90 days', hbars([['Expires ≤ 30 days', mods.filter(m => live(m) && m.expiry && daysTo(m.expiry) >= 0 && daysTo(m.expiry) <= 30).length, 'o2'], ['Expires 31–90 days', mods.filter(m => live(m) && m.expiry && daysTo(m.expiry) > 30 && daysTo(m.expiry) <= 90).length, 'o1'], ['Review due ≤ 90 days', mods.filter(m => live(m) && m.reviewDate && daysTo(m.reviewDate) <= 90).length, 's1'], ['Expired · review required', mods.filter(m => ls(m) === 'Review Required').length, 'o2']], Math.max(1, mods.length / 3)), [], ['', ''])}
    </div>`;
  } else if (tab === 'materials') {
    const mods = S.modules.filter(objFilter), as = S.assets.filter(objFilter);
    const grp = (label, fn) => { const rows = fn(); const mx = Math.max(1, ...rows.flatMap(r => [r[1], r[2]])); return chartCard('mat-' + label, 'By ' + label, 'Modules and materials', `<div class="hb grouped">${rows.map(r => `<div class="hb-group"><span class="hb-gl">${esc(r[0])}</span>${hbars([['Modules', r[1], 'o1'], ['Materials', r[2], 'o2']], mx)}</div>`).join('')}</div>`, rows.map(r => [esc(r[0]), r[1], r[2]]), [label[0].toUpperCase() + label.slice(1), 'Modules', 'Materials'], `<div class="legend"><span><i class="o1"></i>Modules</span><span><i class="o2"></i>Materials</span></div>`); };
    const sts = ['Draft', 'In Review', 'Amendment Requested', 'Rejected', 'Approved'];
    body = `<div class="kpis" style="margin-bottom:18px">${kpi(mods.length, 'Modules', 'Matching the filters', '')}${kpi(as.length, 'Materials', 'Assets matching the filters', '')}${kpi(as.filter(a => live(a)).length, 'Approved materials', 'Have a live version', 'ok')}${kpi(as.filter(isOutdated).length, 'Need update', 'Use an older module version', as.filter(isOutdated).length ? 'bad' : 'ok')}</div>
    <div class="reports-grid">
    ${grp('product', () => S.products.map(p => [p.name, mods.filter(m => m.products.includes(p.id)).length, as.filter(a => a.products.includes(p.id)).length]))}
    ${grp('country', () => S.markets.map(x => [x.name, mods.filter(m => m.markets.includes(x.id)).length, as.filter(a => a.markets.includes(x.id)).length]))}
    ${chartCard('mat-type', 'Materials by type', '', hbars(S.materialTypes.map(t => [esc(t.name), as.filter(a => a.type === t.id).length]), Math.max(1, ...S.materialTypes.map(t => as.filter(a => a.type === t.id).length)), 'o2'), S.materialTypes.map(t => [esc(t.name), as.filter(a => a.type === t.id).length]), ['Material type', 'Materials'])}
    ${grp('status', () => sts.map(s => [s, mods.filter(m => statusOf(m) === s).length, as.filter(a => statusOf(a) === s).length]))}
    </div>`;
  } else if (tab === 'workflow') {
    const wfs = S.workflows.filter(w => !w.hidden && (!F('rwf') || w.id === F('rwf'))).map(w => { const cs = cycles.filter(c => c.wf === w.id || c.wf.startsWith(w.id + '@')); const closed = cs.filter(c => c.outcome !== 'In progress' && c.outcome !== 'Amendment requested'); const ap = cs.filter(c => c.outcome === 'Approved'); return { w, n: cs.length, closed: closed.length, ap: ap.length, rej: cs.filter(c => c.outcome === 'Rejected').length, am: cs.filter(c => c.amendments || c.outcome === 'Amendment requested').length, t: avg(ap.map(c => c.end - c.start)) }; }).filter(x => x.n);
    const tot = wfs.reduce((s, x) => ({ n: s.n + x.n, closed: s.closed + x.closed, ap: s.ap + x.ap, rej: s.rej + x.rej, am: s.am + x.am }), { n: 0, closed: 0, ap: 0, rej: 0, am: 0 });
    const outcomes = [['Approved', tot.ap, 'ok', 'check'], ['Rejected', tot.rej, 'bad', 'x'], ['In progress', tot.n - tot.closed, 'warn', 'clock']];
    body = `<div class="kpis" style="margin-bottom:18px">${kpi(pct(tot.ap, tot.closed) + '%', 'Success rate', tot.ap + ' of ' + tot.closed + ' closed cycles approved', 'ok')}${kpi(pct(tot.am, tot.n) + '%', 'Amendment rate', tot.am + ' of ' + tot.n + ' cycles had an amendment', 'warn')}${kpi(pct(tot.rej, tot.closed) + '%', 'Rejection rate', tot.rej + ' rejected cycles', 'bad')}${kpi(dd(avg(done.map(c => c.end - c.start))), 'Average cycle time', 'Approved cycles', '')}</div>
    <div class="reports-grid">
    ${chartCard('wfout', 'Cycle outcomes', 'All cycles in the period', `<div class="sbar" role="img" aria-label="${outcomes.map(o => o[0] + ' ' + o[1]).join(', ')}">${outcomes.filter(o => o[1]).map(o => `<span class="${o[2]}" style="flex:${o[1]}" data-tip="${o[0]} · ${o[1]} (${pct(o[1], tot.n)}%)"></span>`).join('')}</div><div class="sb-legend">${outcomes.map(o => `<div><span class="lg-key ${o[2]}">${icon(o[3], 'sm')}</span><span>${o[0]}</span><b>${o[1]}</b><span class="pct mono">${pct(o[1], tot.n)}%</span></div>`).join('')}</div>`, outcomes.map(o => [o[0], o[1], pct(o[1], tot.n) + '%']), ['Outcome', 'Cycles', 'Share'])}
    ${chartCard('wfct', 'Average cycle time by workflow', 'Approved cycles · days', hbars(wfs.map(x => [esc(x.w.name), x.t]), Math.max(1, ...wfs.map(x => x.t)), 's1', dd), wfs.map(x => [esc(x.w.name), dd(x.t)]), ['Workflow', 'Average'])}
    </div>
    <section class="panel table-wrap" style="margin-top:18px"><div class="panel-head"><h3>Workflow performance</h3></div><table class="tbl no-pg"><thead><tr><th>Workflow</th><th>Cycles</th><th>Approved</th><th>Success rate</th><th>Amendment rate</th><th>Rejection rate</th><th>Avg cycle time</th></tr></thead><tbody>${wfs.map(x => `<tr><td class="title">${esc(x.w.name)}</td><td class="num">${x.n}</td><td class="num">${x.ap}</td><td class="num">${pct(x.ap, x.closed)}%</td><td class="num">${pct(x.am, x.n)}%</td><td class="num">${pct(x.rej, x.closed)}%</td><td class="num">${dd(x.t)}</td></tr>`).join('') || '<tr><td colspan="7" class="muted">No cycles for these filters.</td></tr>'}</tbody></table></section>`;
  } else {
    const days = +F('rrange', '180'); const since = days ? Date.now() - days * DAY : 0;
    const as = S.assets.filter(a => (!F('rprod') || a.products.includes(F('rprod'))) && (!F('rmkt') || a.markets.includes(F('rmkt'))));
    const reuse = {}; as.forEach(a => uniq(a.blocks.filter(b => b.kind === 'module').map(b => b.moduleId)).forEach(id => { reuse[id] = (reuse[id] || 0) + 1; }));
    const top = Object.entries(reuse).filter(([id]) => modById(id) && (!F('rtype') || modById(id).type === F('rtype'))).sort((a, b) => b[1] - a[1]);
    const multiAsset = top.filter(x => x[1] > 1);
    const ev = S.audit.filter(e => e.ts >= since && !e.auto);
    const byUser = Object.entries(ev.reduce((o, e) => (o[e.user] = (o[e.user] || 0) + 1, o), {})).sort((a, b) => b[1] - a[1]).slice(0, 8);
    const byTeam = S.teams.map(t => [t.name, ev.filter(e => user(e.user).team === t.id).length]).filter(x => x[1]).sort((a, b) => b[1] - a[1]);
    const blocks = as.reduce((n, a) => n + a.blocks.filter(b => b.kind === 'module').length, 0); const newB = as.reduce((n, a) => n + a.blocks.filter(b => b.kind === 'new').length, 0);
    body = `<div class="kpis" style="margin-bottom:18px">${kpi(blocks, 'Module placements', 'Approved modules placed in materials', '')}${kpi(pct(blocks, blocks + newB) + '%', 'Reuse rate', 'Content from approved modules', 'ok')}${kpi(multiAsset.length, 'Modules in 2+ materials', 'Approved once, reused many times', '')}${kpi(byUser.length ? user(byUser[0][0]).name.split(' ')[0] : '—', 'Most active user', byUser.length ? byUser[0][1] + ' actions' : 'No activity', '')}</div>
    <div class="reports-grid">
    ${chartCard('reuse', 'Most reused modules', 'Number of materials using each module', hbars(top.slice(0, 8).map(([id, n]) => [`<button class="linklike" ${goAttr('module', id)}>${esc(modById(id).title)}</button>`, n]), Math.max(1, ...top.map(x => x[1])), 's1'), top.map(([id, n]) => [esc(id + ' · ' + modById(id).title), n]), ['Module', 'Materials'])}
    ${chartCard('multi', 'Modules used across multiple materials', 'Module → materials', multiAsset.length ? `<div class="stack" style="gap:10px">${multiAsset.map(([id]) => `<div><b style="font-size:13px">${esc(modById(id).title)}</b> <span class="mono muted">${id}</span><div class="tags" style="margin-top:4px">${as.filter(a => a.blocks.some(b => b.moduleId === id)).map(a => `<span class="tag">${esc(a.id)}</span>`).join('')}</div></div>`).join('')}</div>` : '<p class="muted">No module is used in more than one material.</p>', multiAsset.map(([id, n]) => [esc(id), n]), ['Module', 'Materials'])}
    ${chartCard('users', 'Most active users', 'Actions recorded in the audit trail', hbars(byUser.map(([id, n]) => [`${esc(user(id).name)} <span class="muted">· ${esc(roleLabel(user(id)))}</span>`, n]), Math.max(1, ...byUser.map(x => x[1])), 's1'), byUser.map(([id, n]) => [esc(user(id).name), esc(roleLabel(user(id))), n]), ['User', 'Role', 'Actions'])}
    ${chartCard('teams', 'Most active teams', '', hbars(byTeam.map(([t, n]) => [esc(t), n]), Math.max(1, ...byTeam.map(x => x[1])), 'o1'), byTeam.map(([t, n]) => [esc(t), n]), ['Team', 'Actions'])}
    </div>`;
  }
  return pageHead('Reports', 'Approval performance, content, materials, workflow and usage. Use the filters to find bottlenecks by product, country, type, workflow, review step and period.') +
  `<div class="tabs" role="tablist" style="margin-bottom:14px">${RTABS.map(t => `<button class="tab ${tab === t[0] ? 'active' : ''}" role="tab" aria-selected="${tab === t[0]}" ${goAttr('reports', null, ` data-tab="${t[0]}"`)}>${t[1]}</button>`).join('')}</div>` + filters + body;
}

/* ===== Users ===== */
const USTEPS = [['Personal details', ['name', 'email'], 'Who is this person?'], ['Function & level', ['fn'], 'The function sets what they work on; the level sets their authority within it.'], ['Team & status', ['team'], 'Which team they belong to and whether they can sign in.'], ['Review & save', [], 'Check the details and the permissions this role grants.']];
function permList(rid, compact) {
  const has = S.roles[rid] || [];
  return `<div class="perm-list ${compact ? 'compact' : ''}">${PERMS.map(p => `<div class="check-row"><span class="${has.includes(p[0]) ? 'ok' : 'no'}">${icon(has.includes(p[0]) ? 'check' : 'x', 'sm')}</span><span class="${has.includes(p[0]) ? '' : 'muted'}">${esc(p[1])}</span></div>`).join('')}</div>`;
}
function viewUsers() {
  const q = F('usq').toLowerCase();
  const rows = S.users.filter(x => (!q || (x.name + x.email + roleLabel(x)).toLowerCase().includes(q)) && (!F('ufn') || x.fn === F('ufn')) && (!F('ulvl') || x.level === F('ulvl')) && (!F('usst') || x.status === F('usst')));
  const nF = f => S.users.filter(x => x.fn === f && x.status === 'Active').length;
  const lastAct = id => { const e = S.audit.filter(a => a.user === id).sort((a, b) => b.ts - a.ts)[0]; return e ? ago(e.ts) : '—'; };
  return pageHead('Users', 'People, their function and level. The role (function + level) decides their permissions; workflows decide where each role takes part.', can(me(), 'manage_users') ? goBtn('Create user', 'user-new', null, 'primary', 'plus') : '') +
  statStrip([...funcIds().map(f => [esc(f), nF(f), '', 'Active', 'ufn', f]), ['Administrators', nF('Administrator'), '', 'Full control', 'ufn', 'Administrator'], ['Inactive', S.users.filter(x => x.status !== 'Active').length, 'dim', 'Cannot sign in', 'usst', 'Inactive']]) +
  `<div class="toolbar">${searchBox('usq', F('usq'), 'Search name, email or role')}${sel('ufn', F('ufn'), [...funcIds(true), 'Administrator'], 'All functions')}${sel('ulvl', F('ulvl'), LEVELS.map(l => [l, levelName(l)]), 'Any level')}${sel('usst', F('usst'), ['Active', 'Inactive'], 'Any status')}${clearBtn(['usq', 'ufn', 'ulvl', 'usst'])}<span class="muted" style="margin-left:auto">${rows.length} of ${S.users.length}</span></div>
  <section class="panel table-wrap"><table class="tbl list-tbl"><thead><tr><th>Name</th><th>Role</th><th>Team</th><th>Authority</th><th>Permissions</th><th>Last activity</th><th>Status</th></tr></thead><tbody>${rows.map(x => { const a = authority(x.fn, x.level);
    return `<tr class="click" ${goAttr('user', x.id)} tabindex="0"><td><div class="row nowrap">${avatar(x)}<div><div class="title">${esc(x.name)}</div><span class="muted email">${esc(x.email)}</span></div></div></td><td><div class="row nowrap" style="gap:6px">${fnBadge(isAdmin(x) ? 'Admin' : x.fn, 'sm')}${esc(isAdmin(x) ? 'Administrator' : x.fn)} ${lvl(x.level)}</div></td><td class="nw">${esc(team(x.team).name)}</td><td style="font-size:12.5px"><span class="row nowrap" style="gap:6px">${icon(a.final ? 'key' : 'eye', 'sm')}${esc(a.short)}</span></td><td class="num">${(S.roles[roleId(x)] || []).length} of ${PERMS.length}</td><td class="nw muted">${lastAct(x.id)}</td><td>${chip(x.status === 'Active' ? 'Active' : 'Inactive')}</td></tr>`; }).join('')}</tbody></table></section>`;
}
function viewUser() {
  const x = S.users.find(u => u.id === UI.route.p.id); if (!x) return viewMissing('User');
  const a = authority(x.fn, x.level); const tasks = tasksFor(x); const acts = S.audit.filter(e => e.user === x.id).sort((p, q) => q.ts - p.ts).slice(0, 6); const self = x.id === me().id;
  return pageHead(esc(x.name), esc(x.email), can(me(), 'manage_users') ? `${goBtn('Edit', 'user-edit', x.id, '', 'edit')}${self ? '' : btn(x.status === 'Active' ? 'Deactivate' : 'Activate', 'user-status', x.status === 'Active' ? 'danger' : 'primary', `data-id="${x.id}"`)}` : '', [['Users', 'users'], [x.name]]) +
  (x.status !== 'Active' ? `<div class="banner" style="margin-bottom:16px">${icon('lock')}<div class="txt"><b>Inactive — cannot sign in</b><p>Their history stays in the audit trail. Activate the account to restore access.</p></div></div>` : '') +
  `<div class="grid cols-main"><div class="stack"><section class="panel"><div class="panel-body row" style="gap:16px;align-items:flex-start">${avatar(x, 'lg')}<div class="stack" style="gap:8px;flex:1"><div class="row"><b style="font-size:18px">${esc(roleLabel(x))}</b>${lvl(x.level)}${chip(x.status === 'Active' ? 'Active' : 'Inactive')}</div>
    <div class="banner ${a.final ? 'ok' : ''}">${icon(a.final ? 'key' : 'eye')}<div class="txt"><b>${esc(a.short)}</b><p>${esc(a.long)}</p></div></div></div></div></section>
    <section class="panel"><div class="panel-head"><h3>Permissions</h3><span class="muted" style="font-size:12px">From the ${esc(roleLabel(x))} role</span><span class="grow"></span>${isAdmin(x) ? '' : goBtn('Edit role permissions', 'roles', null, 'ghost sm', 'key')}</div><div class="panel-body">${permList(roleId(x))}</div></section>
    <section class="panel"><div class="panel-head"><h3>Assigned tasks</h3><span class="chip plain">${tasks.length}</span></div>${tasks.length ? tasks.slice(0, 8).map(t => viewTaskRow(t)).join('') : '<div class="empty"><p>No open tasks.</p></div>'}</section></div>
  <div class="stack"><section class="panel"><div class="panel-head"><h3>Details</h3></div><div class="panel-body"><dl class="kv" style="grid-template-columns:110px 1fr"><dt>Function</dt><dd>${esc(isAdmin(x) ? 'Administrator' : x.fn)}</dd><dt>Level</dt><dd>${esc(levelName(x.level) || 'Not applicable')}</dd><dt>Team</dt><dd>${esc(team(x.team).name)}</dd><dt>Role</dt><dd>${esc(roleLabel(x))}</dd><dt>Status</dt><dd>${esc(x.status)}</dd></dl></div></section>
  <section class="panel"><div class="panel-head"><h3>Recent activity</h3>${can(me(), 'view_audit') ? `<span class="grow"></span><button class="btn ghost sm" data-act="audit-user" data-id="${x.id}">All activity</button>` : ''}</div><div class="panel-body">${viewTimeline(acts, true)}</div></section></div></div>`;
}
function viewUserForm() {
  const editId = UI.route.p.id; const x = editId ? S.users.find(u => u.id === editId) : null;
  if (!UI.udraft || UI.udraft._for !== (editId || 'new')) { UI.udraft = x ? { _for: editId, name: x.name, email: x.email, fn: x.fn, level: x.level || 'Member', team: x.team, status: x.status } : { _for: 'new', name: '', email: '', fn: '', level: 'Member', team: '', status: 'Active' }; UI.udraft.step = 0; UI.udraft.maxStep = x ? USTEPS.length - 1 : 0; UI.udraft.triedSteps = []; }
  const D = UI.udraft; const E = wizErrors(D, USTEPS, validateUser(D, editId)); const err = k => E[k] ? `<span class="err">${E[k]}</span>` : ''; const st = D.step; const hid = i => i === st ? '' : ' hidden';
  const isAdm = D.fn === 'Administrator'; const rid = D.fn ? (isAdm ? 'Administrator' : D.fn + '-' + D.level) : null; const a = D.fn ? authority(D.fn, isAdm ? null : D.level) : null;
  const teams = S.teams.filter(t => (t.active || t.id === D.team) && (!D.fn || t.fn === D.fn)); const title = x ? 'Edit user' : 'Create user';
  const fnIco = f => f === 'Administrator' ? 'key' : fnInfo(f).reviews ? 'shieldcheck' : 'file';
  const fnDesc = f => f === 'Administrator' ? 'Configures and governs the system' : fnInfo(f).desc;
  return pageHead(title, 'Function and level define the role, and the role defines the permissions.', '', x ? [['Users', 'users'], [x.name, 'user', x.id], ['Edit']] : [['Users', 'users'], ['Create user']]) +
  wizBar('user', USTEPS, D) + `<form class="grid cols-main ${D.anim ? (D.anim = false, 'wiz-anim') : ''}" data-form="user" novalidate><div class="stack">${wizHead(USTEPS, D)}
  <section class="panel"${hid(0)}><div class="panel-head"><h3>Personal information</h3></div><div class="panel-body fgrid">
    <div class="field"><label for="u-name">Full name</label><input class="input ${E.name ? 'invalid' : ''}" id="u-name" data-u="name" value="${esc(D.name)}" placeholder="e.g. Ahmed Youssef">${err('name')}</div>
    <div class="field"><label for="u-email">Work email</label><input class="input ${E.email ? 'invalid' : ''}" id="u-email" type="email" data-u="email" value="${esc(D.email)}" placeholder="name@saja.com">${err('email')}</div>
    <div class="field" style="grid-column:1/-1"><span class="hint">${icon('mail', 'sm')} New users receive an invitation email and set their own password on first sign-in.</span></div>
  </div></section>
  <section class="panel"${hid(1)}><div class="panel-head"><h3>Function</h3></div><div class="panel-body"><div class="type-cards" role="radiogroup" aria-label="Function">${[...funcIds(), 'Administrator'].map(f => `<button type="button" class="type-card ${D.fn === f ? 'on' : ''}" data-act="u-fn" data-v="${esc(f)}" role="radio" aria-checked="${D.fn === f}"><span class="type-ico">${icon(fnIco(f), 'sm')}</span><span><b>${esc(f)}</b><span>${esc(fnDesc(f))}</span></span></button>`).join('')}</div>${err('fn')}<p class="muted" style="font-size:12px;margin-top:8px">Functions are managed in <button type="button" class="linklike" ${goAttr('functions')}>Functions</button>.</p></div></section>
  ${isAdm ? `<section class="panel"${hid(1)}><div class="panel-body"><div class="banner">${icon('key')}<div class="txt"><b>Administrators have full control</b><p>They manage users, roles, workflows, SOPs and settings, see every report and the full audit trail, and can act on any approval step.</p></div></div></div></section>` : `<section class="panel"${hid(1)}><div class="panel-head"><h3>Level</h3></div><div class="panel-body stack"><div class="seg" role="radiogroup" aria-label="Level">${LEVELS.map(l => `<button type="button" class="${D.level === l ? 'on' : ''}" data-act="u-level" data-v="${l}" role="radio" aria-checked="${D.level === l}">${levelName(l)}</button>`).join('')}</div><p class="muted" style="font-size:12.5px">${D.fn ? esc(authority(D.fn, D.level).long) : 'Choose a function first.'}</p></div></section>`}
  <section class="panel"${hid(2)}><div class="panel-head"><h3>Team & status</h3></div><div class="panel-body fgrid">
    <div class="field"><label for="u-team">Team</label><select class="select ${E.team ? 'invalid' : ''}" id="u-team" data-u="team">${opt('', D.team, 'Select team')}${teams.map(t => opt(t.id, D.team, t.name)).join('')}</select>${teams.length ? '' : `<span class="hint">No active team for this function yet. <button type="button" class="linklike" data-act="cfg-new" data-k="teams">Create a team</button></span>`}${err('team')}</div>
    <div class="field"><span class="label">Role</span><div class="input" style="display:flex;align-items:center;background:var(--surface-2)">${D.fn ? esc(isAdm ? 'Administrator' : D.fn + ' ' + levelName(D.level)) : '<span class="muted">Set by function and level</span>'}</div></div>
    <div class="field"><span class="label">Status</span><div class="seg">${['Active', 'Inactive'].map(s => `<button type="button" class="${D.status === s ? 'on' : ''}" data-act="u-status" data-v="${s}">${s}</button>`).join('')}</div></div>
  </div></section>
  ${st === USTEPS.length - 1 ? `${D.tried && Object.keys(E).length ? `<div class="banner bad">${icon('alert')}<div class="txt"><b>${Object.keys(E).length} field${Object.keys(E).length > 1 ? 's need' : ' needs'} attention</b><p>Use Edit to go back to that step.</p></div></div>` : ''}
  ${sumGroup('user', 0, 'Personal details', sumRow('Name', esc(D.name)) + sumRow('Email', esc(D.email)))}
  ${sumGroup('user', 1, 'Function & level', sumRow('Function', esc(D.fn)) + sumRow('Level', isAdm ? 'Not applicable' : D.fn ? lvl(D.level) : ''))}
  ${sumGroup('user', 2, 'Team & status', sumRow('Team', D.team ? esc(team(D.team).name) : '') + sumRow('Status', esc(D.status)))}` : ''}
  ${wizFoot('user', USTEPS, D, x ? goAttr('user', x.id) : goAttr('users'), x ? 'Save changes' : 'Create user & send invite')}</div>
  <aside class="stack" style="position:sticky;top:84px"><section class="panel"><div class="panel-head"><h3>Role preview</h3></div><div class="panel-body stack">${a ? `<div class="row"><b>${esc(isAdm ? 'Administrator' : D.fn + ' ' + levelName(D.level))}</b></div><div class="banner ${a.final ? 'ok' : ''}">${icon(a.final ? 'key' : 'eye')}<div class="txt"><b>${esc(a.short)}</b><p>${esc(a.long)}</p></div></div><span class="section-title">Permissions</span>${permList(rid, true)}` : '<p class="muted">Choose a function to see what this person will be able to do.</p>'}</div></section></aside></form>`;
}
function validateUser(D, editId) {
  const e = {};
  if (!D.name.trim()) e.name = 'Enter the full name.';
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(D.email)) e.email = 'Enter a valid email address.';
  else if (S.users.some(u => u.email.toLowerCase() === D.email.toLowerCase() && u.id !== editId)) e.email = 'A user with this email already exists.';
  if (!D.fn) e.fn = 'Choose a function.';
  if (!D.team) e.team = 'Select a team.';
  return e;
}

/* ===== Roles & permissions ===== */
function viewRoles() {
  const ids = [...funcIds().flatMap(f => LEVELS.map(l => f + '-' + l)), 'Administrator']; const groups = uniq(PERMS.map(p => p[2])); const n = rid => S.users.filter(x => roleId(x) === rid && x.status === 'Active').length;
  return pageHead('Roles & Permissions', 'A role is a function plus a level. Tick a box to grant that permission to everyone in the role. The Administrator role always has every permission.', btn('Restore defaults', 'roles-reset', '', '', 'undo')) +
  `<section class="panel table-wrap perm-wrap"><table class="tbl no-pg perm-tbl"><thead><tr><th>Permission</th>${ids.map(r => `<th><div class="perm-h">${fnBadge(r === 'Administrator' ? 'Admin' : r.split('-')[0], 'sm')}<b>${esc(r === 'Administrator' ? 'Administrator' : r.split('-')[0])}</b><span>${esc(r === 'Administrator' ? 'Full control' : levelName(r.split('-')[1]))}</span><span class="muted">${n(r)} ${n(r) === 1 ? 'person' : 'people'}</span></div></th>`).join('')}</tr></thead><tbody>
  ${groups.map(g => `<tr class="perm-group"><td colspan="${ids.length + 1}">${esc(g)}</td></tr>` + PERMS.filter(p => p[2] === g).map(p => `<tr><td class="perm-name" title="${esc(p[3])}">${esc(p[1])}<span class="perm-desc">${esc(p[3])}</span></td>${ids.map(r => { const on = (S.roles[r] || []).includes(p[0]); const locked = r === 'Administrator'; return `<td class="perm-cell"><button type="button" class="pbox ${on ? 'on' : ''}" ${locked ? 'disabled title="Administrators always have every permission"' : `data-act="perm-toggle" data-role="${r}" data-perm="${p[0]}"`} role="checkbox" aria-checked="${on}" aria-label="${esc(p[1])} for ${esc(roleName(r))}">${on ? icon('check', 'sm') : ''}</button></td>`; }).join('')}</tr>`).join('')).join('')}
  </tbody></table></section>
  <div class="grid cols-2" style="margin-top:18px"><section class="panel"><div class="panel-head"><h3>Review hierarchy</h3></div><div class="panel-body stack" style="gap:10px">${reviewFuncs().map(fn => `<div class="hier">${fnBadge(fn, 'sm')}<b>${fn}</b><span class="hier-step">${lvl('Member')} Initial ${fn} review</span>${icon('arrow', 'sm')}<span class="hier-step">${lvl('Lead')} Final ${fn} approval</span></div>`).join('')}<p class="muted" style="font-size:12.5px">Members do the initial review and pass items to their Lead. Leads can return items to the Member and give the final approval for their function with an e-signature.</p></div></section>
  <section class="panel"><div class="panel-head"><h3>How permissions work</h3></div><div class="panel-body stack" style="gap:8px"><div class="check-row"><span class="ok">${icon('check', 'sm')}</span>Permissions apply to every person in the role, immediately.</div><div class="check-row"><span class="ok">${icon('check', 'sm')}</span>Approval steps are assigned by workflow to a function and level.</div><div class="check-row"><span class="ok">${icon('check', 'sm')}</span>Every change is recorded in the audit trail with the previous and new value.</div><div class="check-row"><span class="ok">${icon('key', 'sm')}</span>Administrators are not limited by functional restrictions.</div><div class="check-row"><span class="ok">${icon('team', 'sm')}</span><span>Add a function (for example Pharmacovigilance) in <button class="linklike" ${goAttr('functions')}>Functions</button>; its Member and Lead roles appear here.</span></div></div></section></div>`;
}

/* ===== Organisation & configuration: generated from CONFIG (config.js) ===== */
const viewTeams = () => viewConfig('teams');
const viewProducts = () => viewConfig('products');
const viewMarkets = () => viewConfig('markets');
const viewMaterials = () => viewConfig('materials');

/* ===== Validation SOPs ===== */
const typeLabel = id => S.moduleTypes.some(t => t.id === id) ? mtype(id).name : mat(id).name;
function sopScopeTxt(s) { const sc = s.scope || {}; const parts = [sc.types && sc.types.length ? sc.types.map(typeLabel).join(', ') : '', sc.products && sc.products.length ? productsTxt(sc.products) : '', sc.markets && sc.markets.length ? marketsTxt(sc.markets) : ''].filter(Boolean); return parts.join(' · ') || 'All content'; }
function viewSops() {
  const open = [...S.modules.map(m => [m, 'Module']), ...S.assets.map(a => [a, 'Asset'])].filter(([o]) => ['Draft', 'Amendment Requested', 'Awaiting Lead submission', 'In Review'].includes(statusOf(o)));
  const failing = s => open.filter(([o, k]) => sopApplies(s, o, k) && sopCheck(s, o, k)).length;
  return pageHead('Validation SOPs', 'Requirements checked automatically before submission and before approval. Each SOP can be limited to content types, products or countries.', can(me(), 'manage_sops') ? btn('New SOP', 'sop-new', 'primary', '', 'plus') : '') +
  `<section class="panel table-wrap"><table class="tbl list-tbl"><thead><tr><th>SOP</th><th>Requirement</th><th>Applies to</th><th>Scope</th><th>Failing now</th><th>Active</th><th></th></tr></thead><tbody>${S.sops.map(s => { const f = failing(s); return `<tr><td><div class="title">${esc(s.name)}</div><span class="mono muted">${s.id}</span></td><td style="font-size:12.5px">${esc(SOP_RULES[s.rule])}${s.rule === 'review_window' ? ' · ' + (s.months || 12) + ' months' : ''}<br><span class="muted">${esc(s.guidance)}</span></td><td><span class="tag">${esc(s.appliesTo === 'Both' ? 'Modules & assets' : s.appliesTo + 's')}</span></td><td style="font-size:12.5px">${esc(sopScopeTxt(s))}</td><td>${s.active ? (f ? `<span class="chip bad">${f} item${f > 1 ? 's' : ''}</span>` : '<span class="chip ok">None</span>') : '<span class="muted">—</span>'}</td><td>${can(me(), 'manage_sops') ? toggleBtn(s.active, 'sop-active', `data-id="${s.id}"`, 'Active') : chip(s.active ? 'Active' : 'Inactive')}</td><td>${can(me(), 'manage_sops') ? `<button class="btn sm ghost" data-act="sop-edit" data-id="${s.id}">${icon('edit', 'sm')}Edit</button>` : ''}</td></tr>`; }).join('')}</tbody></table></section>
  <section class="panel" style="margin-top:18px"><div class="panel-head"><h3>When SOPs are checked</h3></div><div class="panel-body grid cols-2"><div class="check-row"><span class="ok">${icon('send', 'sm')}</span><span><b>Before submission.</b> The Material Owner sees ✓ / ⚠ for every SOP and cannot submit while one fails.</span></div><div class="check-row"><span class="ok">${icon('key', 'sm')}</span><span><b>Before approval.</b> Approvers see the same check; the approval button stays disabled until every SOP passes.</span></div></div></section>`;
}

/* ===== Settings ===== */
const SETTINGS = [
  ['Organisation', [['orgName', 'Organisation name', 'text', 'Shown on cover letters and sign-in.']]],
  ['Lifecycle rules', [['expiryWarnDays', 'Expiry warning (days)', 'number', 'Approved content is flagged as Expiring this many days before expiry.'], ['reviewReminderDays', 'Periodic review reminder (days)', 'number', 'Owners are reminded this many days before the periodic review date.'], ['defaultValidityMonths', 'Default validity (months)', 'number', 'Pre-filled expiry for new modules.']]],
  ['Approved Library governance', [['libraryShowExpiring', 'Show expiring content in the library', 'bool', 'When off, content inside the expiry warning window is hidden from the library.']]],
  ['Approval settings', [['requireSignature', 'Require password e-signature for approvals', 'bool', 'Approvers re-enter their password to sign.'], ['adminActsOnAnyStep', 'Administrators can act on any approval step', 'bool', 'Decisions are marked “Recorded by Administrator”.'], ['defaultModuleWorkflow', 'Default workflow for new modules', 'wf', ''], ['newVersionWorkflow', 'Default workflow for new versions', 'wf', 'Pre-selected when a new version of an approved module is submitted.'], ['assetStreamWorkflow', 'Workflow for assets made only of approved modules', 'wfa', 'Assets with new text use the workflow of their Material Type.']]]
];
function viewSettings() {
  if (!UI.setDraft) UI.setDraft = { ...S.settings };
  const D = UI.setDraft; const dirty = SETTINGS.some(([, f]) => f.some(([k]) => String(D[k]) !== String(S.settings[k])));
  const field = ([k, label, type, hint]) => { const id = 'st-' + k;
    const ctl = type === 'bool' ? toggleBtn(!!D[k], 'set-bool', `data-k="${k}"`, label) : type === 'wf' || type === 'wfa' ? `<select class="select" id="${id}" data-set="${k}">${asWorkflows(type === 'wf' ? 'Module' : 'Asset').map(w => opt(w[0], D[k], w[1])).join('')}</select>` : `<input class="input" id="${id}" data-set="${k}" type="${type}" value="${esc(D[k])}" ${type === 'number' ? 'min="1"' : ''}>`;
    return type === 'bool' ? `<div class="set-row"><div><b>${label}</b>${hint ? `<span class="muted">${hint}</span>` : ''}</div>${ctl}</div>` : `<div class="field"><label for="${id}">${label}</label>${ctl}${hint ? `<span class="hint">${hint}</span>` : ''}</div>`; };
  return pageHead('Settings', 'System-wide rules for lifecycle, the Approved Library and approvals. Every change is recorded in the audit trail.', `${dirty ? btn('Discard', 'set-discard', 'ghost') : ''}${btn('Save settings', 'set-save', 'primary', dirty ? '' : 'disabled', 'check')}`) +
  `<div class="grid cols-2">${SETTINGS.map(([title, fields]) => `<section class="panel"><div class="panel-head"><h3>${title}</h3></div><div class="panel-body form">${fields.map(field).join('')}</div></section>`).join('')}
  <section class="panel"><div class="panel-head"><h3>Governance shortcuts</h3></div><div class="panel-body stack" style="gap:8px">${[['roles', 'key', 'Roles & Permissions'], ['functions', 'shieldcheck', 'Functions'], ['workflows', 'workflow', 'Workflows & review hierarchy'], ['sops', 'clipboard', 'Validation SOPs'], ['moduletypes', 'type', 'Module types'], ['channels', 'send', 'Channels'], ['audiences', 'users', 'Audiences'], ['references', 'quote', 'Reference library'], ['audit', 'history', 'Full audit trail'], ['reports', 'chart', 'All reports']].map(([r, ic, l]) => `<button class="task" ${goAttr(r)}>${icon(ic, 'sm')}<span class="body"><b>${l}</b></span>${icon('chevron', 'sm')}</button>`).join('')}</div></section>
  <section class="panel"><div class="panel-head"><h3>Workspace data</h3></div><div class="panel-body stack"><p class="ink2" style="font-size:13px">Restore the initial SAJA workspace: products, countries, users, workflows, SOPs, modules, assets and the audit trail. This cannot be undone.</p><div>${btn('Restore initial workspace', 'reset-open', 'danger', '', 'undo')}</div></div></section></div>`;
}
